## Gaussian Naive Bayes classifier

In [31]:
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report, f1_score, confusion_matrix

In [32]:
iris = load_iris()
test_idx = [0,50,100,140]

train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

#### fit() --- For training an algorithm
#### predict() --- For performing prediction
#### transform() --- transforming data from one format to other format

#### fit_predict() --- training + prediction
#### fit_transform() --- training + transforming

In [33]:
clf = GaussianNB()
clf.fit(train_data, train_target)

GaussianNB()

In [34]:
print(test_target) #it will print the testing label
predictions = clf.predict(test_data)
print(predictions) #it will predict the label for test data

[0 1 2 2]
[0 1 2 2]


In [35]:
# Evaluate the accuracy
accuracy = accuracy_score(test_target, predictions)
print(f"Accuracy: {accuracy:.2f}")
print("F1 score:",f1_score(test_target, predictions,average='macro'))

Accuracy: 1.00
F1 score: 1.0


## Multinomial Naive Bayes classifier

In [36]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [37]:
# Load the 20 Newsgroups dataset
newsgroups = fetch_20newsgroups(subset='all', remove=('headers', 'footers', 'quotes'))
len(newsgroups.data)

18846

In [38]:
print(newsgroups.data[:500])

["\n\nI am sure some bashers of Pens fans are pretty confused about the lack\nof any kind of posts about the recent Pens massacre of the Devils. Actually,\nI am  bit puzzled too and a bit relieved. However, I am going to put an end\nto non-PIttsburghers' relief with a bit of praise for the Pens. Man, they\nare killing those Devils worse than I thought. Jagr just showed you why\nhe is much better than his regular season stats. He is also a lot\nfo fun to watch in the playoffs. Bowman should let JAgr have a lot of\nfun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final\nregular season game.          PENS RULE!!!\n\n", 'My brother is in the market for a high-performance video card that supports\nVESA local bus with 1-2MB RAM.  Does anyone have suggestions/ideas on:\n\n  - Diamond Stealth Pro Local Bus\n\n  - Orchid Farenheit 1280\n\n  - ATI Graphics Ultra Pro\n\n  - Any other high-perf

In [39]:
newsgroups.target

array([10,  3, 17, ...,  3,  1,  7])

In [40]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(newsgroups.data, newsgroups.target, test_size=0.2, random_state=42)

In [41]:
# Convert text data to a bag-of-words representation
vectorizer = CountVectorizer(stop_words='english', max_features=5000, ngram_range=(1,2))

X_train_bow = vectorizer.fit_transform(X_train)
X_test_bow = vectorizer.transform(X_test)

In [42]:
vectorizer.get_feature_names_out()

array(['00', '00 00', '000', ..., 'zionist', 'zip', 'zone'], dtype=object)

In [43]:
df = pd.DataFrame(X_train_bow.todense(),columns=vectorizer.get_feature_names_out
())
df

,00,00 00,000,01,02,03,03 03,04,040,05,...,young,young people,youth,yugoslavia,z5,zero,zionism,zionist,zip,zone
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15071,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15072,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15073,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15074,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [44]:
# Create and train a Naive Bayes classifier
classifier = MultinomialNB()
classifier.fit(X_train_bow, y_train)

# Make predictions on the test set
predictions = classifier.predict(X_test_bow)

In [45]:
# Evaluate the accuracy
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy:.2f}")

# Classification report
print("Classification Report:")
print(classification_report(y_test, predictions))

Accuracy: 0.63
Classification Report:
              precision    recall  f1-score   support

           0       0.48      0.60      0.53       151
           1       0.52      0.63      0.57       202
           2       0.78      0.04      0.07       195
           3       0.44      0.69      0.54       183
           4       0.59      0.65      0.62       205
           5       0.73      0.74      0.74       215
           6       0.79      0.61      0.69       193
           7       0.65      0.74      0.69       196
           8       0.36      0.68      0.47       168
           9       0.76      0.77      0.76       211
          10       0.92      0.72      0.81       198
          11       0.85      0.67      0.75       201
          12       0.59      0.58      0.58       202
          13       0.85      0.71      0.77       194
          14       0.79      0.66      0.72       189
          15       0.64      0.76      0.69       202
          16       0.59      0.69      0.63

In [46]:
print(confusion_matrix(y_test, predictions))

[[ 91   1   0   0   1   1   1   2   8   0   0   1   0   1   3   8   9   4
    8  12]
 [  5 127   0  21   7   9   0   3  13   0   1   0   8   1   4   1   0   0
    0   2]
 [  1  37   7  63  22  38   1   3   9   1   0   3   6   0   0   1   0   0
    1   2]
 [  0   7   0 127  24   3   4   2   3   0   0   1   9   2   0   0   0   1
    0   0]
 [  2   5   0  20 134   1   4   6  15   0   0   1  10   3   1   2   1   0
    0   0]
 [  1  27   0   9   5 160   0   1   7   1   0   0   1   1   1   1   0   0
    0   0]
 [  0   3   0  19  16   1 118   9   6   3   0   5   6   0   4   0   1   1
    1   0]
 [  1   3   0   2   2   0   3 146  22   0   0   0   4   0   2   2   5   0
    3   1]
 [  1   1   0   2   1   1   5  19 114   7   1   0   4   1   0   2   7   0
    1   1]
 [  2   1   0   0   0   0   1   2  19 162   7   0   0   1   0   8   1   1
    4   2]
 [  3   0   0   1   2   1   0   2  16  23 143   0   1   1   0   1   0   0
    4   0]
 [  5   4   1   2   1   1   1   1   6   0   1 135  11   1   3   1